---
title: | 
 **Carta de intención Laboratorio de Ciencia Social Abierta
 (LISA-COES)**
linkcolor: blue
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Estimados Dr. Juan Carlos Castillo y equipo,

Soy seminarista de grado de la carrera de sociología en la Universidad de Chile y me desempeño fundamentalmente en estudios laborales y sindicalismo con enfoques cuantitativos y cualitativos hace aproximadamente cuatro años. Durante esos años en investigaciones tanto académicas como con organizaciones de la sociedad civil he procurado diseñar, aplicar y difundir la investigación de manera rigurosa y susceptible a la crítica y colaboración. A partir de cátedras y aprendizajes de ciencia social abierta pude encontrar una serie de principios y herramientas que guían la aplicación práctica de una ciencia llana a la transparencia, colaboración y reproducibilidad. Así, adhiriendo y promoviendo la ciencia abierta he aprendido a manejar sistemas y plataformas para el acceso público a datos, control de versionamientos y trabajo colaborativo centralizado, softwares de código abierto y publicaciones libres. He puesto a prueba estos principios y herramientas de la ciencia abierta en mis trabajos de investigación sobre relaciones laborales y sindicalismo, contando con experiencia actualizada al respecto. Es por esto que creo poder aportar desde mis intereses y experiencias a su Laboratorio de Ciencia Social Abierta como pasante de investigación. 

Siendo miembro del [Centro de Investigación Político Social del Trabajo](https://cipstra.cl/) he investigado sobre sindicalismo y relaciones laborales levantando un Observatorio Sindical y un [Repositorio de Estadísticas Sindicales](https://repositoriosindical.netlify.app/) junto a otros colegas. En estas experiencias, así como en iniciativas personales de la misma materia, he practicado la ciencia abierta disponiendo de los datos utilizados, trabajando con sistemas de control de versiones y colaborativos (Git/Github), elaborando trabajos reproducibles mediante el uso de software de código abierto (Rstudio/ Jupyter Notebook) y difundiendo los resultados de investigación de manera auditable (Open Science Framework). Por ejemplo, el RES es una iniciativa autogestionada de investigadores del trabajo que estudia, construye y centraliza datos cuantitativos sobre el sindicalismo chileno junto a otros indicadores de las relaciones laborales. Este es un [repositorio abierto](https://github.com/ObservatorioSindical), de acceso público, reproducible y colaborativo orientado a aportar al mundo sindical y las políticas públicas. [Individualmente](https://github.com/Andreas-Lafferte), también he dispuesto de diversas investigaciones y datos sobre relaciones laborales y sindicatos bajo los mismos principios y herramientas de la ciencia abierta. En todas estas experiencias he desarrollado sistemáticamente la elaboración y validación de encuestas, recolección de datos para su posterior procesamiento y análisis junto a la generación de plataformas web e informes. Desempeñando un trabajo riguroso con la concreción de objetivos y comprometido con el mundo sindical y académico, me guío bajo una sociología pública del quehacer investigativo, dispuesto a colaborar y entregar conocimientos reflexivos a la sociedad civil.

Los objetivos y principios que promueve el Laboratorio de Ciencia Social Abierta se alinean con mis experiencias e intereses sobre la investigación social. Creo que el conocimiento se construye socialmente, siendo una responsabilidad ética disponer de herramientas para el acceso, transparencia y reproducibilidad de la investigación para la comunidad científica y la ciudadanía. En ese sentido, espero poder contribuir a su laboratorio en el desarrollo de herramientas para la apertura de datos, reproducibilidad de análisis y publicaciones libres, así como también en todos los productos y objetivos atingentes al proyecto. Mi disposición horaria es total tanto en jornada completa como en media jornada para el proyecto.

Sin más que agregar, agradezco humildemente su disposición y tiempo aludiendo a la oportunidad abierta. Ante cualquier consulta o comentario, favor contactarme con los datos indicados en esta carta. 

Saludos cordiales, 

Andreas Lafferte

+569 58754230 / andreas.lafferte.tamayo@gmail.com   