---
output:
  pdf_document: default
  html_document: default
---

# Agradecimientos {-}
<div style="text-align: left">

<p>"Yo, como tú,<br>
amo el amor, la vida, el dulce encanto<br>
de las cosas, el paisaje<br>
celeste de los días de enero.<br>

También mi sangre bulle<br>
y río por los ojos<br>
que han conocido el brote de las lágrimas.<br>

Creo que el mundo es bello,<br>
que la poesía es como el pan, de todos.<br>

Y que mis venas no terminan en mí<br>
sino en la sangre unánime<br>
de los que luchan por la vida,<br>
el amor,<br>
las cosas,<br>
el paisaje y el pan,<br>
la poesía de todos."<br>

Roque Dalton</p>


<div style="text-align: justify">

A mi madre Gloria y a mi padre Dantón, quienes me han dado todo y más, quienes me enseñaron a amar y a amar la vida. A mi hermano Jacques, quien en su forma de ser cada día me enseña algo nuevo. A mis abuelas Lola y Magaly, por su cariño férreo e inagotable. Por ustedes, la vida. 

A mis amigos y amigas; Martín, Belén, Vanessa, Jan, Salvador y Gabriela. En ustedes he encontrado cobijo, comprensión y por sobre todo mucho cariño para tener la confianza de ser quien soy. Mención especial a Martín y a Belén, compañeros y amigos de varias noches de conversaciones extensas y profundas, de penurias y alegrías, gracias por estar y por alentarme siempre.

A mis hermanos y hermanas, compañeros y compañeras de La Minga, lugar que tanto me ha entregado, donde tanto he aprendido y que me ha dado el honor de conocer a personas de esas que te acompañan toda una vida de lucha. Gracias por ser aquel espacio que siempre busqué.

A mi profesor guía Juan Carlos Castillo, por su comprensión, paciencia y confianza hacía mí, por envalentonarme a creen en mis capacidades, por las largas conversaciones sobre la vida y la sociología, y por siempre considerarme como una persona con algo que decir y aportar. También a mis otros profesores y profesoras que fueron parte de mi camino formativo, gracias por enseñarme a querer esta disciplina  

Espero que esta tesis sea, en algún grado, reflejo de todo lo aprendido, y espero estar a la altura de los desafíos que siguen pues en mí cargo con cada palabra, gesto y cariño que me han entregado. 

Sin prisa, sin pausa. 





