---
output:
  pdf_document: default
  html_document: default
---
# Introducción. ¿Mayores percepciones de conflicto social? {-#intro}

> *“The rich and the poor in a country with a highly unequal distribution of wealth . . . may live next to each other, but their lives do not intersect. . . . In such societies, neither the rich nor the poor have any sense of a shared fate. . . . In turn, each group looks out for its own interests and is likely to see the demands of the other as conflicting with its own well-being.” ---(Rothstein and Uslaner, 2005, p.46).*

<div style="text-align: justify">

Esta cita ilustra un hecho importante; el creciente distanciamiento entre grupos y clases sociales en la actualidad. Los altos niveles de desigualdad económica, la explotación, los cierres sociales y los estilos de vida tan marcados, son algunas características para describir el comportamiento de la estratificación social en el capitalismo contemporáneo. Asimismo, producen una visión conflictiva de la realidad bajo la defensa de los intereses propios ante los de otros. Esta visión del ‘nosotros contra ellos’ deja abierta la pregunta de si estamos observando síntomas de un conflicto de clases más profundo y si ello se traduce en la percepción subjetiva del mismo. ¿Es posible pensar, al menos desde el plano subjetivo, que existen conflictos de clase?

En las últimas décadas, el conflicto social ha sido un rasgo característico de la sociedad chilena debido a sus altos niveles de desigualdad económica y ciclos de movilización social. Por mucho tiempo Chile fue considerado un ejemplo de crecimiento económico, transición democrática y estabilidad social, sin embargo, es uno de los países con mayor desigualdad económica en Latinoamérica y entre los países desarrollados, cuestión expresada en las amplias brechas de ingresos, la excesiva concentración de la riqueza en el 1% y la ausencia de políticas redistributivas [@floresTopIncomesChile2019; @solimanoCapitalismoChilenaProsperidad2018]. En paralelo, la conflictividad social ha “resurgido” por medio de movilizaciones y la política contenciosa, con demandas orientadas hacia la desmercantilización y reconocimiento de derechos sociales básicos, llegando a cuestionar las bases del régimen político de la transición [@donoso2017a; @garretonGranRupturaInstitucionalidad2016a; @sommaDiscontentCollectiveProtest2017a]. Si bien el conflicto social es uno de los temas más tratados en la sociología [@collinsConflictSociologySociological2009b], en Chile su abordaje se ha centrado en enfoques como la política contenciosa o la movilización de recursos [@medelMarchasOcupacionesBarricadas2016a]. Poca consideración ha tenido la dimensión subjetiva del conflicto, la cual es especialmente relevante para determinar una polarización de actitudes y opiniones de los sujetos. En este ámbito, recientes investigaciones han demostrado un aumento de la percepción subjetiva del conflicto a razón de eventos políticos y la agudización de desigualdades económicas, dando cuenta de un amplio grado de desconexión social entre grupos verticalmente estructurados 
[@atriaInformeResultadosEstudio2021b; @castilloPercepcionConflictoChile2015a; @perezEncontrandoQueNunca2013; -@perezPercepcionesConflictoConfianza2020]. Con todo, la conflictividad social es un rasgo característico de la sociedad Chilena que experimenta amplias desigualdades y ciclos de protestas, abriendo la interrogante sobre la percepción subjetiva del conflicto y su aumento. 

Estudiar las percepciones de conflicto social se torna especialmente relevante si se considera que, por un lado, más allá de poder relacionarse con la ocurrencia de conflictos reales, entrega evidencia sobre las actitudes, opiniones y valores que desarrollan los individuos respecto a una estructura social jerárquica y la posesión desigual de recursos [@lewin-epsteinDistributiveJusticeAttitudes2003; @whitefieldSocialInequalityAssessments2013b; @zagorskiPerceptionSocialConflicts2006b]. Por otro, si bien es útil en el orden de hacer más cohesiva la sociedad, también es una herramienta para comprender que las percepciones de conflicto no son solo desigualdades de opinión [@laschRebelionElitesTraicion1996b], sino que revelan diferencias estructuralmente formadas [@kluegelBeliefsStratification1981a; @rodrikGlobalizationSocialConflict1997]. En países con alta desigualdad económica y protestas, como Chile, es necesario escudriñar quienes perciben más conflicto, cómo y por qué ciertos factores sociales lo afectan [@hertelConflictPerceptions272019b]. 

No deja de ser significativo mencionar las tesis del fin de las clases y la pérdida de relevancia de los conflictos verticales ante los cambios de la sociedad industrial. A partir de la muerte anunciada del proletariado por la desindustrialización y modificaciones en la estructura de empleo, además del avance de las políticas redistributivas y prosperidad económica, las desigualdades modernas serían más complejas y sin una base clasista, por lo que los conflictos sociales no se sustentarían en desigualdades jerárquicas [@beckRiskSocietyNew1992; @pakulskiFoundationsPostclassAnalysis2005; @pakulskiDeathClass1996a]. Estos enunciados, aunque con menor entusiasmo, también tomaron lugar en Chile a través de la tesis de la mesocratización de la estructura social, el apaciguamiento de los conflictos “económicos” y la fragmentación de la identidad tradicional de la clase trabajadora y la clase media [@espinozaEstratificacionMovilidadSocial2013a; @leonEstratificacionSocialChilena2001; @ruizChilenosBajoNeoliberalismo2014]. A contrapelo de estas sentencias, hoy la tesis de la mesocratización y la ausencia de conflictos sociales es fuertemente criticada en Chile. Recientes investigaciones han puesto en duda la idea de una sociedad de clase media a razón de la debilidad estructural para su asentamiento [@barozetEsUstedClase2017a; @garretonGranRupturaInstitucionalidad2016a; @perezClasesSocialesSectores2018]. Por su parte, la clase social continuaría siendo un factor clave para explicar la conflictividad social en términos de polarización de actitudes y acciones contenciosas [@donoso2017a; @gaudichaudFisurasNeoliberalismoChileno2015; @gayoTerciarizacionChileDesigualdad2016a; @perezEncontrandoQueNunca2013; -@perezClassConsciousnessMature2014]. Con las movilizaciones de octubre de 2019 la conflictividad social se ha vuelto un punto común de discusión, planteándose como la cristalización de múltiples protestas que no han cesado durante la década [@joignantObservatorioConflictos20202020] y la manifestación de una pugna entre elites minoritarias y la ciudadanía, discrepando con el anunciado declive de los conflictos verticales [@ruizOctubreChilenoIrrupcion2020].

En Chile, las percepciones de conflicto social han sido motivo de escasas investigaciones. La percepción de conflicto social se refiere a cómo los sujetos captan/describen un conflicto social determinado entre dos clases o grupos verticalmente organizados [@hertelConflictPerceptions272019b]. En ese sentido, indican “la medida en que los individuos experimentan su entorno como caracterizado por tales relaciones antagónicas” [@hertelConflictPerceptions272019b, pp.2]. De acuerdo con estas investigaciones, las percepciones de conflicto social se verían determinadas tanto por factores objetivos, tales como la posición de clase, el estatus social, el sexo y el ingreso, así como por actitudes subjetivas, por ejemplo la desigualdad percibida o expectativas políticas [@castilloPercepcionConflictoChile2015a; @perezEncontrandoQueNunca2013; -@perezPercepcionesConflictoConfianza2020]. Es interesante mencionar que estas percepciones han variado durante el tiempo, más aún en un contexto de alta desigualdad económica y movilizaciones sociales [@castilloPercepcionConflictoChile2015a]. El informe de Atria & Rovira Kaltwasser [-@atriaInformeResultadosEstudio2021b, pp.46-47] da cuenta de lo anterior, en donde se aprecia un aumento de las percepciones de conflicto social entre grupos verticalmente organizados (ricos y pobres, empresarios y trabajadores), pero esta percepción es distinta entre las elites y la ciudadanía. Esto demuestra que dos grupos sociales no ven de la misma forma un mismo fenómeno, lo cual invita a interrogarse por las razones y maneras en que esto ocurre. 

En cierto modo, las investigaciones nacionales sobre las percepciones de conflicto social han instalado una dicotomía de factores explicativos. Por un lado, existe un consenso en que las percepciones de conflicto social serían mayormente explicadas por factores subjetivos, tales como actitudes, preferencias y otras percepciones. En ese sentido, las expectativas políticas (como las metas del país) afectarían las percepciones de conflicto social en tanto inducen ciertos patrones de comportamiento y preferencias aun cuando no se correspondan con las características sociodemográficas [@castilloPercepcionConflictoChile2015a]. Por otro lado, se ha demostrado que factores objetivos, tales como la clase social, el ingreso y características sociodemográficas, inciden en las percepciones de conflicto social. Por ejemplo, Pérez [-@perezEncontrandoQueNunca2013, pp.103] estudia la percepción de conflicto entre trabajadores y directivos desde una perspectiva de clase. Sus hallazgos permiten concluir que: (i) la posición objetiva de clase representa una serie de mecanismos que configuran los intereses y ciertas actitudes subjetivas de sus miembros, y (ii) que esta percepción varía según la categoría de clase, por lo que no puede ser desestimada para el análisis del conflicto.

Esta discusión también ocurre a la hora de explicar las fuentes y dinámicas de la conflictividad chilena en general. Ciertas posturas sostienen que el conflicto carece de un contenido de “clase” y se asocia más bien a aspectos individuales del malestar, tales como la frustración ante la promesa incumplida del desarrollo equitativo, crisis de legitimidad del sistema político y disputas por exclusión ante los cierres sociales [@espinozaEstratificacionMovilidadSocial2013a; @garretonGranRupturaInstitucionalidad2016a; @sommaSomma2015Protestas2015]. Sin embargo, como sostienen otras investigaciones, también es cierto que buena parte de la conflictividad tiene motivos económicos vinculados a la estratificación social, como el resurgimiento del sindicalismo chileno [@aravenaRenacerHuelgaObrera2009a; @campusanoConflictividadLaboralPolitizacion2017], el conflicto previsional, los conflictos medioambientales y estudiantiles [@donoso2017a; @gaudichaudFisurasNeoliberalismoChileno2015]. Dada la discrepancia en la literatura y la ausencia de una agenda de investigación sobre la conflictividad de clases percibida, esta investigación se enfoca en los determinantes objetivos de las percepciones de conflicto social. En particular, se interroga por la relación entre la posición de clase y las percepciones de conflicto en Chile durante los años 1999 a 2019, debido a la relevancia teórica de reconsiderar las condiciones objetivas de clase para abordar el conflicto en una sociedad que, como la Chilena, posee una estructura de clases reticente al cambio y que es fuente de diversas desigualdades [@perezClasesSocialesSectores2018; @gayoTerciarizacionChileDesigualdad2016a]. Además, es preciso aportar con evidencia actualizada sobre la relación entre la posición de clase y las percepciones de conflicto social a luz de los eventos políticos y movilizaciones en la última década. 




### Pregunta de investigación {-}

*¿Cómo cambia la relación entre la clase social y las percepciones de conflicto social a partir del rol del contexto económico-laboral e institucional entre 1999-2019?*

### Objetivo {-}

Analizar cómo cambia la relación entre la clase social y las percepciones de conflicto social de acuerdo con las variaciones contextuales de determinantes económicos-laborales e institucionales entre 1999-2019.

### Objetivos específicos {-}

*O.E.1* – Analizar la relación entre la posición de clase y las percepciones de conflicto social entre 1999-2019.

*O.E.2* – Analizar el rol de la desigualdad económica sobre la relación entre la posición de clase y las percepciones de conflicto social entre 1999-2019.

*O.E.3* – Analizar el rol del grado de coordinación salarial sobre la relación entre la posición de clase y las percepciones de conflicto social entre 1999-2019. 


