# Discusión {#discussion}

<div style="text-align: justify">

En cuanto al rol de la clase social, los resultados de los modelos multinivel demuestran que el efecto de la posición de clase es positivo y significativo, sustentando lo planteado hipotéticamente respecto a que los individuos de clase trabajadora percibirían mayor conflicto social que los individuos de clase capitalista ($H_{1}$). Esto tiene una serie de implicancias para el estudio de las percepciones de conflicto considerando la ausencia del análisis de clase en la mayoría de las investigaciones recientes. En primer lugar, entrega evidencia que contradice aquellos argumentos que, en sus versiones más extremas, plantearon precipitadamente la “muerte de las clases” o, al menos, afirmaron que la clase había desaparecido como categoría explicativa satisfactoria frente a las nuevas desigualdades más "complejas" [@pakulskiDeathClass1996a]. En segundo lugar, este hallazgo es consistente con investigaciones previas que han defendido la relevancia de las desigualdades de clase para abordar distintos fenómenos subjetivos asociados al conflicto [@wrightUnderstandingClass2015; @dodsonEconomicChangeClass2017; @lindhClassPositionPolitical2020a]. En términos sustantivos, mis resultados apoyan lo encontrado por Edlund & Lindh [-@edlundDemocraticClassStruggle2015a] y Pérez [-@perezClassUnionMembership2022] en la medida que los individuos ubicados en las clases bajas/subordinadas perciben mayores conflictos que quienes se ubican en las clases altas/privilegiadas. Analizando la percepción general de los conflictos sociales desde un enfoque marxista de las clases, esta investigación contribuye a la literatura al explicar el efecto de la clase social denotando cómo la posición objetiva de los individuos en las relaciones de dominación y explotación define un conjunto de intereses materiales y estrategias para realizarlos que no solo son disímiles, sino que potencialmente antagónicos. Siguiendo a Wright [-@wrightClassCountsComparative1997a], tales intereses asientan, a su vez, diversas experiencias que configuran activamente las percepciones subjetivas de los individuos, representando el mecanismo por el cual la posición de clase es explicativa de diferencias significativas en la percepción de conflictos.

Los resultados de los modelos también subrayan la importancia de la distinción entre clases propietarias y no propietarias dentro de los países. Siguiendo a Pérez [-@perezClassUnionMembership2022], el que los individuos pertenecientes a posiciones de clase trabajadora tengan niveles similares de percepción de conflictos que son comparativamente mayores a los de los individuos de clases capitalistas -grandes propietarios y pequeños empleadores-, es indicativo de que poseer medios productivos, contratar fuerza de trabajo y dominarla dentro de la producción define percepciones distintas sobre las tensiones intergrupales. Bajo un enfoque marxista, esto se explicaría tanto por el modo en que las relaciones de propiedad determinan, en parte, lo que la gente posee para asegurar sus intereses, así como también por la manera en que las relaciones de explotación definen lo que estas tienen que hacer para obtener su bienestar económico. Precisamente, y en línea con el argumento de Wright [-@wrightClases1994], las posiciones más distantes en el mapa de clases tienden a tener percepciones opuestas en la medida que sus intereses son distintos y la realización de los mismos dependen de su capacidad de perjudicar la obtención del bienestar de la otra clase. Esto se traduce en que las clases subordinadas, en tanto excluidas en las relaciones de propiedad y explotadas en el ámbito de la producción, perciban mayores conflictos debido a su desventaja económica y la merma de sus intereses [@perezClassUnionMembership2022; @andersenPolarizingEffectEconomic2012a]. Por su parte, las clases privilegiadas observan menos tensiones no solo debido a que su derechos de propiedad les otorgan una mayor ventaja económica, sino porque además tienden a percibir el logro de sus intereses como resultado de su propio esfuerzo y cualificación antes que como producto del menoscabo sobre otras clases [@lindhClassPositionPolitical2020a].

A pesar de lo anterior, igualmente existen diferencias relevantes dentro de las clases no propietarias. Aunque los datos utilizados no permitieron realizar todas las distinciones propuestas por el esquema de Wright [-@wrightClassCountsComparative1997a], específicamente respecto a los bienes de autoridad, los resultados indican que la percepción de conflicto es comparativamente menor entre las posiciones asociadas a los estratos medios en relación con las posiciones más subordinadas de la clase trabajadora[^17]. Esto es consistente con la literatura que ha demostrado que la percepción de conflictos tiende a incrementarse a medida que se “desciende” por la estructura de clases, es decir, que aunque las posiciones medias perciban mayores conflictos que la altas, las tensiones intergrupales son percibidas con mayor intensidad en las clases más bajas [@edlundDemocraticClassStruggle2015a; @perezClassUnionMembership2022]. Una posible explicación a estas diferencias entre las clases asalariadas -asumiendo una medición incompleta del esquema de Wright- se asocia a la situación “contradictoria” de las clases medias en las relaciones de explotación. En concreto, los altos grados de cualificación de estas posiciones las conducen a tener intereses materiales contradictorios debido a que, por las credenciales que controlan en el mercado, se apropian de una “renta de cualificación” y gozan de mayor autonomía en el seno de la producción, lo que las convierte en clases que aunque son explotadas en una dimensión, son al mismo tiempo explotadoras en otra [@wrightClassCountsComparative1997a]. Además, a esto hay que añadir el hecho de que su condición de ventaja relativa las acerca a la movilidad e inestabilidad en la estructura social, afectando sus actitudes y percepciones [@hertelConflictPerceptions272019a].

Un último elemento relevante a mencionar sobre el efecto de la posición de clase es lo que ocurre con los individuos pertenecientes a la pequeña burguesía. Como indican los resultados, los individuos de esta clase tienden a percibir mayores conflictos que aquellos pertenecientes a la clase de los grandes propietarios. Este hallazgo difiere de lo sugerido por Pérez [-@perezClassUnionMembership2022] y se alinea con lo encontrado por Edlund & Lindh [-@edlundDemocraticClassStruggle2015a] sobre la clase de los autoempleados, muy posiblemente debido a la manera en que se midió la percepción de conflictos. Ciertamente, Pérez [-@perezClassUnionMembership2022] demuestra que cuando se examina la percepción de conflicto netamente laboral, los individuos de la pequeña burguesía no perciben una conflictividad comparativamente mayor a los grandes y pequeños empleadores -entre otras razones por sus altos grados de autonomía laboral-, mientras que, por su parte, Edlund & Lindh [-@edlundDemocraticClassStruggle2015a] mostraron que cuando se analiza la percepción general de conflictos verticales, los autoempleados sí perciben mayores tensiones en comparación a los grandes propietarios o los profesionales altamente cualificados de servicios. En ese sentido, la inclusión de amplios o amorfos grupos sociales en la medición del conflicto, específicamente de los ricos y los pobres, produciría resultados diferentes en las percepciones de la pequeña burguesía. Siguiendo a Jansen [-@jansenSelfemploymentAtypicalAutonomous2019], una posible explicación a este hallazgo puede asociarse a las condiciones de alto riesgo económico que enfrentan segmentos del autoempleo. Aunque se ha tendido a considerar a los autoempleados como una clase homogénea, altamente autónoma y económicamente conservadora, buena parte de la literatura reciente sobre el mercado laboral ha demostrado que se caracterizarían más bien por poseer condiciones de gran inseguridad económica, desempeñándose en empleos precarios y con baja autonomía, lo cual podría generar que sus intereses materiales sean de hecho contrarios a los de los los grupos más privilegiados de la sociedad como los ricos o grandes empleadores.

En línea con investigaciones anteriores, los resultados de los modelos también muestran que los individuos afiliados a organizaciones sindicales perciben mayores conflictos sociales que quienes no están afiliados [@perezClassUnionMembership2022; @hadlerIstKlassenkonfliktUeberholt2003a; @ringqvistHowUnionMembership2020a]. Aunque los métodos utilizados no permiten determinar la direccionalidad _causal_ del efecto, este resultado sí permite apoyar lo planteado hipotéticamente ($H_{2}$). Siguiendo la teoría de las redes sociales, este hallazgo da cuenta de que, a pesar del innegable declive del movimiento sindical en diversos países desde 1980 [@hodderDoesStrikeAction2017], organizaciones colectivas como los sindicatos continúan jugando un rol clave en facilitar la polarización de distintas percepciones de sus miembros mediante diversos recursos materiales, culturales y socio-organizacionales [@edwardsResourceMobilizationTheory2013]. En detalle, el rol de las organizaciones sindicales en incrementar las percepciones de conflicto podría deberse tanto a las oportunidades estructurales que estas organizaciones les ofrecen a sus miembros para involucrarse en situaciones conflictivas, así como a los diversos mecanismos de socialización de identidades, valores o habilidades políticas que estos experimentarían al interior de los sindicatos y que terminarían por influir en sus percepciones [@passySocialNetworksIndividual2001; @kerrisseyLaborUnionsPolitical2018]. Además, el que los sindicatos potencien la percepción de conflicto entre grupos que no se remiten estrictamente al ámbito laboral podría estar planteando la posibilidad, aún incierta, de que las problemáticas que estas organizaciones plantean a sus miembros estén “sobrepasando” los confines del lugar de trabajo y se extiendan hacia otras temáticas sociales [@fregeUnionRevitalizationStrategies2003].

En cuanto a las variables de nivel contextual, la evidencia sugiere que el grado de desigualdad económica de los países -medida a partir de la concentración del ingreso- se relaciona positiva y significativamente con la percepción de conflicto, apoyando dos conclusiones recurrentes en la literatura: por un lado, que cuanto mayor es la desigualdad, mayores tienden a ser las percepciones de conflicto en los individuos ($H_{3a}$) y, por otro, que este efecto varía considerablemente entre países [@edlundDemocraticClassStruggle2015a; @hertelConflictPerceptions272019a; @hadlerSocialConflictPerception2017a]. Ahora bien, lo que este estudio aporta a la discusión sobre el efecto de la desigualdad es su medición a partir de la concentración del ingreso en los quintiles más ricos y más pobres de la población ya que, como se mencionó, estratifica de manera más notoria las ventajas y desventajas entre individuos y se enfoca en los grupos extremos de la distribución del ingreso, volviéndose un indicador más idóneo para examinar la polarización social [@milanovicGlobalInequalityNew2016a]. En ese sentido, y de acuerdo con las teorías del conflicto social, el efecto positivo de la concentración del ingreso se debería a que la desigualdad económica actúa como una fuerza social que afecta tanto la realización de intereses de los individuos como sus condiciones materiales [@salverdaIntroduction2011b], ocasionando que el contexto de dificultades asociadas al consumo, las privaciones económicas y las distancias entre clases incrementen las visiones conflictivas sobre la distribución de recursos entre grupos poseedores y desposeídos [@karakocEconomicInequalityIts2013]. 

Sin embargo, los resultados de las interacciones entre niveles añaden matices a este argumento. Si bien se demostró que las clases subordinadas perciben mayores conflictos que las clases privilegiadas, esta relación cambia en contextos de alta desigualdad. Como sugiere la evidencia, el efecto de la desigualdad no es parejo entre las clases sociales puesto que, cuando la desigualdad aumenta, las clases subordinadas tienden a reducir su percepción de conflicto mientras que los individuos de clase capitalista la incrementan. Este estrechamiento de las diferencias contradice la hipótesis de mayor polarización entre clases en países más desiguales ($H_{3b}$) y se asemeja a lo encontrado en estudios recientes sobre percepciones de la desigualdad [@haddonHowDoesActual2022]. Siguiendo estas investigaciones, una posible explicación a este hallazgo puede encontrarse en las hipótesis de la teoría del riesgo [@soltEconomicInequalityDemocratic2008]. De acuerdo con este enfoque, el tipo de efecto que los cambios macroeconómicos generan en las actitudes de los individuos depende del estrato social al cual pertenezcan ya que entrañan diferentes grados de aversión al riesgo [@fraileCorrespondenceObjectiveSubjective2014]. En ese sentido, lo que conduciría a que los individuos de clase capitalista incrementen su percepción de conflicto mientras que los individuos de clase trabajadora la reduzcan sería el mayor grado de aversión al riesgo que tendrían los primeros cuando la desigualdad económica aumenta puesto que, por lo que poseen, experimentarían un coste marginal más alto que los individuos de clases subordinadas que ya se encuentran estructuralmente en desventaja y que tendrían percepciones menos dependientes de los cambios en el nivel de desigualdad [@haddonHowDoesActual2022]. Esto también podría explicar por qué el patrón entre clases no se invierte cuando aumenta la desigualdad, _i.e._, que aunque la clase capitalista eleve su percepción de conflicto, esto no supone que las categorías de clase trabajadora dejen de percibir mayores conflictos que las clases privilegiadas, dando cuenta de la relevancia de los factores estructurales de las desigualdades de clase [@wrightClassCountsComparative1997a]. 


Respecto a la dimensión institucional del conflicto, los resultados revelan que el grado de corporativismo de los países se asocia con menores tensiones sociales percibidas por los individuos, apoyando la hipótesis propuesta ($H_{4}$). Sin negar las importantes contribuciones de investigaciones anteriores que se interesaron por las consecuencias económicas de los acuerdos corporativistas [@edlundDemocraticClassStruggle2015a], este hallazgo coincide más bien con otros estudios que han enfatizado el aspecto político del corporativismo como un reductor más relevante de las percepciones de conflicto [@perezClassUnionMembership2022; @ringqvistHowUnionMembership2020a]. Tanto para la literatura del neo-corporativismo como para la escuela de los recursos de poder, el efecto de las instituciones corporativistas se debería a que estas suponen la institucionalización del conflicto social en la medida que, por un lado, disponen de mecanismos estructurales y funcionales que permiten la resolución institucional del conflicto [@jahnChangingGuardTrends2016] y, por el otro, cristalizan un mayor balance entre los recursos de poder de los mayores actores junto al Estado en la determinación de la política económica, dando por resultado que las tensiones sociales se trasladen a la esfera política [@driffillSocialCorporatismSuperior1994; @korpiPowerResourcesEmployerCentered2006a]. En ese sentido, las reglas, normas y marcos interpretativos que generan estos diseños institucionales producirían un determinado "contexto para el conflicto social" que afectaría las percepciones subjetivas de los individuos [@jacksonActorsInstitutions2010], variando sustancialmente entre aquellos países que poseen estos canales institucionales y aquellos en los que se encuentran débilmente presentes o ausentes. Por último, este hallazgo respalda lo planteado por Pérez [-@perezClassUnionMembership2022] al agregar un segundo matiz a la tesis de la convergencia institucional producida por la globalización neoliberal puesto que, sin desconocer sus importantes consecuencias en la política económica de los países [@baccaroCommonNeoliberalTrajectory2011a], las diferencias institucionales entre naciones corporativistas y no corporativistas continúan siendo cruciales para explicar diferencias significativas en el conflicto percibido por los ciudadanos.


Finalmente, la evidencia sugiere que el tiempo no se asocia con mayores percepciones de conflicto entre los individuos, contradiciendo la hipótesis exploratoria ($H_{5}$). Ciertamente, los cambios en los niveles de desigualdad económica en las últimas décadas junto al resurgimiento de las protestas sociales en diversos países podrían instigar a los individuos a captar mayores conflictos [@hertelConflictPerceptions272019a]. Sin embargo, este hallazgo demuestra que el tiempo por sí mismo no implica un incremento en el conflicto percibido, contribuyendo a la literatura que se ha interesado por su dimensión temporal [@hadlerSocialConflictPerception2017a]. Aun así, este resultado debe interpretarse con precaución. Una posible explicación al efecto del tiempo puede asociarse a la presencia de determinados países en las diferentes olas bajo estudio, no obstante, mediante un análisis de observaciones influyentes[^18] se pudo dar cuenta de que tanto la dirección como la significancia del coeficiente se mantienen cuando se remueven los casos más influyentes. Así, una explicación más plausible para este resultado puede encontrarse en la dimensión longitudinal de los datos. Como demostraron investigaciones previas, parte de la variación contextual de las percepciones de conflicto puede atribuirse a los cambios longitudinales de características de los países, y aunque tales esfuerzos no han hallado resultados sustantivos, emplearon un método que permite estimar correctamente el efecto del tiempo [@edlundDemocraticClassStruggle2015a; @hadlerSocialConflictPerception2017a]. En ese sentido, el uso del tiempo como una covariable antes que como una dimensión de la estructura jerárquica de los datos puede estar oscureciendo el verdadero efecto del cambio en el tiempo, además de sobreestimar el efecto de ciertas variables contextuales que han variado longitudinalmente _dentro_ de los países [@schmidt-catranRandomEffectsMultilevel2016]. En definitiva, que el tiempo muestre un efecto negativo puede ser una primera aproximación para investigar otras características contextuales de los países que, en su variación temporal, puedan influir en la percepción subjetiva del conflicto social.


# Conclusiones {#conclusion}

<div style="text-align: justify">

En las últimas décadas, diferentes formas de conflicto social han resurgido alrededor del mundo como consecuencia del aumento de la desigualdad económica y la concentración de la riqueza. Caracterizados como “tiempos contenciosos,” distintos países han experimentado el regreso de las protestas sociales y la emergencia de una renovada crítica contra las desigualdades, especialmente hacia aquellas relacionadas con temáticas redistributivas [@dellaportaSocialMovementsTimes2015]. En este contexto, diversos estudios se han preguntado por el grado en el que los individuos perciben (o no) los conflictos sociales entre grupos, particularmente entre aquellos organizados verticalmente como los ricos y los pobres o los trabajadores y los empresarios [cf. @edlundDemocraticClassStruggle2015a; @hadlerIstKlassenkonfliktUeberholt2003a; @ringqvistHowUnionMembership2020a]. Aunque algunos estudios más recientes han mostrado una percepción entre moderada y fuerte del conflicto social en diferentes sociedades, además de una asociación positiva con la desigualdad económica [@hertelConflictPerceptions272019a; @hadlerSocialConflictPerception2017a; @delheyPerceptionGroupConflicts2008b], hasta ahora se ha desestimado considerablemente el papel de la clase social en el conflicto percibido, a pesar de que ha demostrado seguir siendo relevante para abordar diversos fenómenos subjetivos [cf. @haddonHowDoesActual2022; @langsaetherMoreSelfinterestWhy2020]. Al mismo tiempo, importantes preguntas sobre cómo la desigualdad contextual y los marcos institucionales de los países pueden moderar el efecto de la clase social se han mantenido inciertas. El presente estudio pretendió cubrir estos vacíos abordando la siguiente pregunta de investigación: ¿En qué medida la clase social afecta a las percepciones de conflicto social y cómo esta relación cambia a partir del rol del contexto económico e institucional entre 1999-2019?


Los análisis empíricos revelan que la posición objetiva de clase es un determinante relevante de las percepciones de conflicto. Utilizando un enfoque neomarxista de las clases, los resultados muestran que los individuos pertenecientes a las clases subordinadas -como los trabajadores no calificados- tienden a percibir mayor conflicto social que los individuos pertenecientes a la clase de los grandes propietarios, apoyando la hipótesis general. La clase *aún importa* en la medida que la posición que ocupan los individuos en las relaciones de dominación y explotación entrañan intereses materiales diferentes e inclusive antagónicos sobre la distribución de recursos, los cuales representan el mecanismo principal que conecta la posición de clase de los individuos con sus percepciones subjetivas [@wrightClassCountsComparative1997a]. Por otra parte, los resultados indican que los individuos afiliados a organizaciones sindicales perciben mayores conflictos que quienes no lo están, sustentando un hallazgo recientemente retomado por la literatura en el marco de relevar la importancia de las organizaciones sociopolíticas en el desarrollo del conflicto [@perezClassUnionMembership2022; @ringqvistHowUnionMembership2020a].


En cuanto a las variables de nivel contextual, la evidencia sugiere que la desigualdad económica -medida como la concentración del ingreso- incrementa la percepción de conflicto en los individuos, apoyando un hallazgo largamente planteado en investigaciones anteriores [@hertelConflictPerceptions272019a; @hadlerSocialConflictPerception2017a]. No obstante, al momento de analizar cómo la relación entre la posición de clase y el conflicto percibido puede ser moderada por la desigualdad económica, los resultados muestran que esta última tiene un efecto diferencial entre las clases. En contra de mi hipótesis de mayor polarización entre clases en contextos de mayor desigualdad, las interacciones entre niveles muestran que, cuando la desigualdad aumenta, las posiciones de clase subordinadas -como los trabajadores no cualificados y cualificados- tienden a reducir su percepción de conflicto mientras que los grandes propietarios la aumentan. Además, los resultados indican que son las clases medias o “contradictorias” las que más reducen su percepción de conflicto en relación con los grandes propietarios ya que el efecto moderador de la desigualdad es más notable entre estas clases. Por último, los resultados revelan que en países donde existen marcos institucionales corporativistas las percepciones de conflicto tienden a ser menores que en los países liberales o pluralistas, en la medida que tales arreglos representan la institucionalización del conflicto social y el traslado de las tensiones sociales al plano político [@korpiPowerResourcesApproach1985; @ringqvistHowUnionMembership2020a].


En conjunto, estos resultados tienen diversas implicancias para el estudio sociológico del conflicto, así como para la agenda de investigación de las percepciones de conflicto. Primero, estos hallazgos permiten posicionar a la dimensión subjetiva del conflicto como un eje central de análisis. Aunque la preocupación por el estudio del conflicto social ha crecido a la luz de las protestas contemporáneas, la manera en que las tensiones sociales se traducen subjetivamente no ha ocupado un rol preponderante en la sociología. Retomando esta línea de investigación, este estudio se ha centrado en el campo específico de las percepciones de conflicto vertical, pero en el contexto de un interés más amplio sobre cuestiones teóricas y empíricas superpuestas, como la interrelación entre las percepciones de los individuos y el sistema de estratificación [@kluegelBeliefsStratification1981a], así como el papel de los contextos económicos e institucionales de los países, siendo todas ellas centrales para el análisis del conflicto [@hadlerIstKlassenkonfliktUeberholt2003a]. Determinar quienes perciben más conflicto, cómo y por qué ciertos factores lo afectan es crucial no solo para conocer la manera en que los individuos perciben a los grupos que componen la estructura social, sino que también para vislumbrar las pautas de polarización social y las dinámicas que pueden adquirir los conflictos “reales” [@kriesbergConstructiveConflictsEscalation2012]. En ese sentido, este estudio permite sostener que los conflictos verticales o redistributivos aún perviven en gran parte de la población en paralelo con otras formas de conflicto -como los horizontales-, siendo lo característico de la conflictividad actual no la primacía absoluta de un tipo de antagonismo, sino que más bien la predominancia de ciertos conflictos tanto “viejos” como “nuevos” que coexisten y se complementan [@dellaportaSocialMovementsIntroduction2006].


Segundo, este estudio contribuye a la investigación empírica sobre cómo las desigualdades de clase afectan las percepciones subjetivas del conflicto, revitalizando su importancia. La clase social ha sido tradicionalmente uno de los predictores más relevantes para examinar los intereses, actitudes y disposiciones de los individuos con importantes consecuencias políticas y sociales [@botteroStratificationSocialDivision2005]. Sin embargo, el análisis de clase -y por extensión el vínculo entre la clase y la subjetividad individual- ha sido fuertemente cuestionado en las últimas décadas en la medida que la clase habría desaparecido -e inclusive “muerto”- como una categoría explicativa satisfactoria ante las nuevas desigualdades más complejas [@pakulskiDeathClass1996a; @clarkAreSocialClass1991]. Mis resultados contradicen tales cuestionamientos y se suman al de otros esfuerzos [cf. @andersenSocialClassEconomic2015; @dodsonEconomicChangeClass2017; @kulinClassValuesAttitudes2013] al demostrar la importancia de estudiar el conflicto percibido a través de los lentes de clase en tanto continúa mostrando signos de ser un vehículo relevante de polarización social [@edlundDemocraticClassStruggle2015a]. Como sostuvo Wright [-@wrightUnderstandingClass2015], el propósito del análisis de clase no es demostrar la primacía explicativa de la clase sobre todo tipo de fenómenos, sino que posicionarlo como un factor explicativo más que puede ser (o no) más importante para determinados objetos de estudio. Esta investigación demostró que trayendo de vuelta los factores económicos y estructurales se pueden observar interesantes variaciones en el conflicto percibido, planteando nuevas interrogantes en un mundo en donde muchas personas continúan reconociendo persistentes divisiones económicas [@eidlinClassFormationClass2014].


Una mayor contribución empírica de este estudio al campo específico de las percepciones de conflicto es lo que ocurre entre la posición de clase y el conflicto percibido en contextos de alta desigualdad económica. Siguiendo la teoría del conflicto [@karakocEconomicInequalityIts2013], se esperaba que, a medida que la desigualdad aumente, las clases subordinadas incrementarían su percepción de conflicto ante la agudización de la deprivación económica, mientras que las clases privilegiadas la reducirían o mantendrían debido a que su posición en la estructura social las protegería de las consecuencias de la desigualdad [@haddonHowDoesActual2022; @dellaportaSocialMovementsTimes2015]. Sin embargo, los resultados mostraron lo contrario. El que la clase capitalista incremente su percepción de conflicto mientras que la clase trabajadora la reduzca a medida que la desigualdad aumenta contradice los supuestos más clásicos de la teoría del conflicto y se acerca más a las explicaciones provenientes de las teorías del riesgo [@haddonHowDoesActual2022]. Así, lo que este estudio sugiere es que, en contextos de alta desigualdad, las clases sociales poseen diferentes percepciones de conflicto debido a sus distintos grados de aversión al riesgo, y si bien esto no implica que las clases subordinadas dejen de percibir mayor conflicto que las clases privilegiadas, ilustra que la desigualdad económica tiende a polarizar más en la parte superior de la estructura social y menos en su parte más baja. 

Este estudio cuenta con algunas limitaciones que llaman a interpretar los resultados con cautela. La primera limitante se asocia a la dimensión longitudinal de los datos. Si bien en esta investigación se incluyó el efecto del tiempo como una covariable de control, esto no necesariamente permite capturar los cambios longitudinales de las características de los países. Debido a que los datos utilizados son comparativos y, a su vez, longitudinales al nivel de los países [@fairbrotherTwoMultilevelModeling2014], existe una fuente de variación y en consecuencia un efecto aleatorio asociado a las características de los países que varían *dentro* de ellos en el tiempo. Por tanto, esta fuente de variación podría estimarse de otra manera con mayor sofisticación, por ejemplo, descomponiendo el efecto transversal y longitudinal de los países, lo que no solo permitiría disminuir la heterogeneidad no observada entre estos grupos [@schmidt-catranRandomEffectsMultilevel2016], sino que también agregaría la posibilidad de analizar si los cambios en el tiempo de determinadas características de los países suponen variaciones significativas en el conflicto percibido. Otra limitante se relaciona con la condición endógena de la membresía sindical. Esto implica un desafío para estudiar el efecto de la membresía sindical en la percepción de conflicto ya que esta última puede afectar a la primera. Aunque no era el interés de este estudio determinar la dirección causal del efecto, algunas formas de lidiar con lo anterior son: i) controlar por variables composicionales a nivel individual -como la educación, ocupación e ideología política- y por factores estructurales -como el sistema de seguridad social o el tipo de relaciones laborales- para evitar el efecto de selección del sindicato [@kerrisseyLaborUnionsPolitical2018]; o bien, ii) utilizar técnicas de variables instrumentales para estimar la causalidad del efecto [@bollenInstrumentalVariablesSociology2012].


A partir de los hallazgos revelados en este estudio, surgen distintas preguntas que necesitan ser abordadas en futuras investigaciones. Además de lidiar con las limitantes señaladas, estos estudios podrían avanzar en mejores formas de medición de las percepciones de conflicto en dos sentidos: por un lado, mediante el uso de factores latentes que capturen adecuadamente un fenómeno complejo como el conflicto subjetivo y, por el otro, a partir de indicadores que especifiquen los motivos del conflicto, ya que el uso de ítems generales puede estar midiendo otros aspectos subjetivos -como las experiencias o creencias- que no necesariamente dan cuenta del reconocimiento de una oposición de intereses entre grupos. Otro aspecto a profundizar en futuras pesquisas es analizar el conflicto percibido mediante otras conceptualizaciones y mediciones de clase social, particularmente a través de otros mecanismos de las desigualdades de clase que tienen consecuencias relevantes en las actitudes y percepciones de los individuos, tales como las identidades de clase, normas o prácticas culturales [@botteroClassIdentitiesIdentity2004; @langsaetherMoreSelfinterestWhy2020]. A este respecto, combinar el análisis de clase con la literatura sobre justicia distributiva podría ser una línea de investigación prometedora en el campo de las percepciones de conflicto en la medida que a la base de cualquier tipo de conflicto se encuentran percepciones y juicios sobre lo justo y lo legitimo de la desigualdad [@deutschJusticeConflict2011]. Una última proyección es analizar por medio de estudios de caso el efecto moderador de la desigualdad económica en la relación entre la clase social y la percepción de conflicto. Ahondar en este interesante hallazgo parece ser un siguiente paso lógico de investigación, puesto que podría arrojar nuevas luces sobre cómo y por qué la desigualdad económica tiene un efecto diferencial entre las clases sociales, especialmente entre las clases medias. 







[^17]: En otros modelos no mostrados se estimó el efecto de la posición de clase cambiando la categoría de referencia por la clase de los trabajadores no calificados. Los resultados indican que, además de que las clases capitalistas o privilegiadas obtienen menores valores en la escala de percepción de conflictos que la categoría de clase de referencia, las posiciones de clases medias -supervisores calificados y expertos no directivos- también perciben menores conflictos (coeficientes significativos al 95% de confianza). 

[^18]: Ver Figura \@ref(fig:fig12) del [Apéndice](#apendiceb). Para determinar si los casos influyentes apalancan el coeficiente de la variable tiempo se estimó un modelo (no mostrado) removiendo a Chipre y Hungría. Los resultados mostraron que la dirección negativa y el nivel de significancia (p < .001) del coeficiente no cambiaron.